name: pactto
description: "Pactto"
publish_to: 'none'
resolution: workspace
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  dominio: ^0.1.0
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  pdf: ^3.13.1
  printing: ^5.15.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DejaVuSans.ttf
    - assets/fonts/DejaVuSans-Bold.ttf
    - assets/logo_padrao.jpg
